- op: add
  path: "/spec/template/spec/securityContext"
  value:
    fsGroup: 1000
- op: add
  path: "/spec/template/spec/containers/0/securityContext"
  value:
    readOnlyRootFilesystem: true
    runAsUser: 1000
    runAsNonRoot: true
- op: add
  path: "/spec/template/spec/containers/0/resources"
  value:
    limits: 
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 1
      memory: 1Gi
