version: 2.1

orbs:
  architect: giantswarm/architect@4.14.2

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          executor: "app-build-suite"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-api-provider-openstack"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/
