version: 2.1

orbs:
  architect: giantswarm/architect@4.12.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: "package and push chart"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "cluster-api-provider-openstack"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/
