apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    cert-manager.io/inject-ca-from: giantswarm/capo-serving-cert
  labels:
    app.giantswarm.io/branch: '{{ .Values.project.branch }}'
    app.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-openstack
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capo-mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capo-webhook-service
      namespace: giantswarm
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-openstackcluster
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.openstackcluster.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclusters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capo-webhook-service
      namespace: giantswarm
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-openstackclustertemplate
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.openstackclustertemplate.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackclustertemplates
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: capo-webhook-service
      namespace: giantswarm
      path: /mutate-infrastructure-cluster-x-k8s-io-v1alpha4-openstackmachine
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: default.openstackmachine.infrastructure.cluster.x-k8s.io
  rules:
  - apiGroups:
    - infrastructure.cluster.x-k8s.io
    apiVersions:
    - v1alpha4
    operations:
    - CREATE
    - UPDATE
    resources:
    - openstackmachines
  sideEffects: None
