{{ if eq (include "resource.app.unique" .) "false" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: capo-controller-manager
    {{- include "labels.infrastructure" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
{{ end }}
