apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    application.giantswarm.io/branch: '{{ .Values.project.branch }}'
    application.giantswarm.io/commit: '{{ .Values.project.commit }}'
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ .Chart.Name }}'
    app.kubernetes.io/version: '{{ .Chart.AppVersion }}'
    cluster.x-k8s.io/provider: infrastructure-openstack
    helm.sh/chart: '{{ .Chart.Name }}'
  name: capo-manager
  namespace: '{{ .Release.Namespace }}'
