resources:
  - tmp/infrastructure-components.yaml

images:
  - name: giantswarm/kaas/capi-openstack-controller:dev
    # once https://github.com/kubernetes-sigs/kustomize/issues/947 is solved
    # we could change back to a more well formated line
    # e.g.:
    #   newName: '{{ .Values.registry.domain }}/{{ .Values.infrastructure.image.name }}'
    #   newTag: '{{ .Values.tag }}'
    newName: "{{.Values.registry.domain}}/{{.Values.infrastructure.image.name}}"
    newTag: "{{.Values.tag}}"

patchesJson6902:
  # add giantswarm specific labels
  # ~1 must be used to escape / - https://github.com/kubernetes-sigs/kustomize/issues/907
  # patch CAPO controller
  - target:
      version: v1
      kind: Namespace
      name: capo-system
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: capo-controller-manager
      namespace: capo-system
    path: patches/giantswarm-common-labels.yaml
  - target:
      version: v1
      kind: Service
      name: capo-webhook-service
      namespace: capo-system
    path: patches/giantswarm-common-labels.yaml
  - target:
      version: v1
      kind: ServiceAccount
      name: capo-manager
      namespace: capo-system
    path: patches/giantswarm-common-labels.yaml
  # patch RBAC
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: Role
      name: capo-leader-election-role
      namespace: capo-system
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRole
      name: capo-manager-role
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: RoleBinding
      name: capo-leader-election-rolebinding
      namespace: capo-system
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: rbac.authorization.k8s.io
      version: v1
      kind: ClusterRoleBinding
      name: capo-manager-rolebinding
    path: patches/giantswarm-common-labels.yaml
  # patch CRDs
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: openstackmachines.infrastructure.cluster.x-k8s.io
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: openstackmachinetemplates.infrastructure.cluster.x-k8s.io
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: openstackclusters.infrastructure.cluster.x-k8s.io
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: apiextensions.k8s.io
      version: v1
      kind: CustomResourceDefinition
      name: openstackclustertemplates.infrastructure.cluster.x-k8s.io
    path: patches/giantswarm-common-labels.yaml
  # patch certmanager manifests
  - target:
      group: cert-manager.io
      version: v1
      kind: Certificate
      name: capo-serving-cert
      namespace: capo-system
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: cert-manager.io
      version: v1
      kind: Issuer
      name: capo-selfsigned-issuer
      namespace: capo-system
    path: patches/giantswarm-common-labels.yaml
  # patch webhook
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: MutatingWebhookConfiguration
      name: capo-mutating-webhook-configuration
    path: patches/giantswarm-common-labels.yaml
  - target:
      group: admissionregistration.k8s.io
      version: v1
      kind: ValidatingWebhookConfiguration
      name: capo-validating-webhook-configuration
    path: patches/giantswarm-common-labels.yaml

  # apply fixes for kube-linter findings
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: capo-controller-manager
      namespace: capo-system
    path: patches/kube-linter-patches.yaml

