apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    control-plane: capo-controller-manager
    {{- include "labels.infrastructure" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-webhook
  namespace: {{ include "resource.default.namespace" . }}
