tag: v0.5.3

infrastructure:
  image:
    name: capi-openstack/capi-openstack-controller

crdConvertOnly: true

ports:
  healthz: 9440
  metrics: 8080
  webhook: 9443

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

watchfilter: capi

serviceType: managed

registry:
  domain: k8s.gcr.io