---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capo-controller-manager
  namespace: capo-system
spec:
  template:
    spec:
      containers:
        - name: manager
          resources:
            limits:
              cpu: 0.5
              memory: 1Gi
            requests:
              cpu: 0.5
              memory: 1Gi
