---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capo-controller-manager
  namespace: capo-system
spec:
  template:
    spec:
      containers:
        - name: manager
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
